import Head from "next/head";
import { ContactList } from "../components/ContactList";
import { RegisterBox } from "../components/RegisterBox";
import styled from "styled-components";
import styles from "../styles/Home.module.css";

const Container = styled.div`
  height: 30vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <RegisterBox />
        <ContactList />
      </Container>
    </div>
  );
}
